# General Settings
encoding: utf-8
# Site settings
title: Barebones
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
# baseurl: "/barebones"
# url: "https://wini3d.github.io/barebones/"
locale: en
github_username:  wini3d

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
  - jemoji  
