# General Settings
encoding: utf-8
# Site settings
title: Barebones
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: "/jek"
# url: "https://wini3d.github.io/barebones/"
locale: en
github_username:  wini3d

repository: "rontrek/jek"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
  - jemoji  

staticman:
  # Name of repository, for use with Staticman
  # repository: "wini3d/minimaj"
  branch: "master"
